language: java
jdk:
- oraclejdk8
after_success:
- mvn clean test
- mvn jacoco:report
- mvn coveralls:report -DrepoToken="${COVERALLS_TOKEN}"
env:
  global:
  - secure: P1sls5bwyLqrG4g7U6+c52wNn8ES0lAG+7sga2w3die2Au1cYEtZJtvchvc3SPoWZy2e0GwSJrvdy4es8QhAOQiBVi+8Bx8pRU9Jf9gLzoDS8rlYQiN8u68QsRFBjFnWzIdJcuc57gjw7LaiSmU2+duGaYoAcfyoaXeojccEZJnApP2CRcj/1Py1DUn9dFlyWoJ68WG7eA2yd8Ryfz9XN75lyYZC8NvbWe5Xv7t1Ex7CUJhRM4SM5fLNWIlsCpisNuVfrYn4JGW8ps2bgJpN4Ak08rR8wZwGdx4Z1Lkayi2k4QmGpxb+hiKP1ZajPnlu4Kox9p7r5oJaT7PFrm2s+bvA36TVSgpnGhTUm/D43P1GDW9r7v2kGgEj081KkEJzLiwwnpCUD4cuR33wFQM+E5CSJiynLifWjj2tgK75B5ZO8nHif9CJWtYRxKAIICXoY1N3WOjUrC6Xkv5tNhcZBWkfJa8rqlvVrtIM92YNp/PLJoJjPZHs4iNCpaLISapici05+Jso9ddSJsHGnl8G4fMt02lE0K0p4A25FMWyiQZrbMB443FOkkXMUh+CAwT+KNowVa91n2SJTC2CxzJSC2JipZ2BsNQ78M1Nwbw6WKTwkQTHsFZlk57YqloWd9hKdjMWvVBBO5c+nocECNMBk6ZaiIBOTbCutNo6a9UpUiU=
